import { fileURLToPath } from "node:url";

import babel from "@rolldown/plugin-babel";
import tailwindcss from "@tailwindcss/vite";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import react, { reactCompilerPreset } from "@vitejs/plugin-react";
import { nitro } from "nitro/vite";
import { RECOMMENDED_RULES, TANSTACK_START_RULES } from "oxlint-plugin-react-doctor";
import { defineConfig } from "vite-plus";

const reactDoctorRules = {
  ...RECOMMENDED_RULES,
  ...TANSTACK_START_RULES,
};

// `tanstackStart()` rewrites `createServerFn(...).handler(fn)` into a client RPC stub, which
// makes server-function handlers unimportable under Vitest, and its transform breaks plain
// unit tests. Nitro only matters for the deploy build. Drop both when Vitest is driving.
// See .claude/rules/common/testing.md.
const isVitest = process.env.VITEST === "true";

const srcPath = fileURLToPath(new URL("./src", import.meta.url));

export default defineConfig({
  fmt: {
    // `.agents/`, `.claude/`, `.cursor/` and `.serena/` are written by external tool
    // installers (skills-lock.json sync, Serena). Formatting them would be reverted on the
    // next sync and buries our own diffs under ~150 unrelated files. `src/data/cache/` is
    // generated by `vp run generate:passport` and must stay byte-identical to its output.
    ignorePatterns: [
      "**/routeTree.gen.ts",
      ".agents/**",
      ".claude/**",
      ".cursor/**",
      ".serena/**",
      "src/data/cache/**",
    ],
    sortImports: {
      partitionByComment: true,
    },
    sortPackageJson: {
      sortScripts: true,
    },
    // `true` = class/className only. The `functions: ["cn"]` entry went with `src/utils/cn.ts`,
    // deleted per closed decision #12 — the repo has no conditional-className site to compose.
    sortTailwindcss: true,
  },
  lint: {
    categories: {
      correctness: "error",
    },
    env: {
      browser: true,
      node: true,
    },
    // Same rationale as `fmt.ignorePatterns`: these are vendored by external tool installers.
    // `denyWarnings: true` means a warning in one of them would block every commit.
    ignorePatterns: ["**/routeTree.gen.ts", ".agents/**", ".claude/**", ".cursor/**", ".serena/**"],
    jsPlugins: [{ name: "react-doctor", specifier: "oxlint-plugin-react-doctor" }],
    options: {
      denyWarnings: true,
      typeAware: true,
      typeCheck: true,
    },
    overrides: [
      {
        files: ["src/router.tsx", "*.config.ts"],
        rules: {
          "no-default-export": "off",
        },
      },
      {
        files: ["src/routes/**"],
        rules: {
          "react-doctor/no-multi-comp": "off",
          "react-doctor/only-export-components": "off",
        },
      },
      {
        // The documented exception: `scripts/**` runs under plain Node, which does not resolve
        // tsconfig `paths`, so relative specifiers with explicit `.ts` extensions are mandatory
        // there. See .claude/rules/typescript/project-structure.md.
        files: ["scripts/**"],
        rules: {
          "no-restricted-imports": "off",
        },
      },
      // The unidirectional-import approximation .claude/rules/typescript/project-structure.md
      // describes: oxc has no `import/no-restricted-paths`, so `shared → features → routes` is
      // expressed as `no-restricted-imports` patterns per layer. An override *replaces* the base
      // rule rather than merging with it, so each one repeats the relative-import ban.
      {
        files: ["src/domain/**", "src/data/**"],
        rules: {
          "no-restricted-imports": [
            "error",
            {
              patterns: [
                {
                  group: ["~/features/*", "~/features/**", "~/routes/*", "~/routes/**"],
                  message:
                    "共有レイヤ（domain/ data/）から feature/route を参照できません。共有側へ引き上げてください。",
                },
                {
                  group: ["./*", "../*"],
                  message: "src/ 内は `~/` エイリアスのみ。相対importは scripts/ だけの例外です。",
                },
              ],
            },
          ],
        },
      },
      {
        files: ["src/features/**"],
        rules: {
          "no-restricted-imports": [
            "error",
            {
              patterns: [
                {
                  group: ["~/routes/*", "~/routes/**"],
                  message: "feature から route を参照できません。共有側へ引き上げてください。",
                },
                {
                  group: ["./*", "../*"],
                  message: "src/ 内は `~/` エイリアスのみ。相対importは scripts/ だけの例外です。",
                },
              ],
            },
          ],
        },
      },
    ],
    plugins: ["react", "react-perf", "import", "jsx-a11y", "promise"],
    rules: {
      ...reactDoctorRules,
      // Named by .claude/rules/common/coding-style.md and project-structure.md as the
      // enforcement behind "no import cycles" and the `~/`-only rule. Both were documentation
      // only until now (audit #17 findings 3, 4 and 5). `src/routeTree.gen.ts` is generated and
      // already in `ignorePatterns`, so the relative-import ban needs no carve-out for it.
      "import/no-cycle": "error",
      "no-default-export": "error",
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["./*", "../*"],
              message: "src/ 内は `~/` エイリアスのみ。相対importは scripts/ だけの例外です。",
            },
          ],
        },
      ],
    },
  },
  staged: {
    "*.{js,jsx,ts,tsx,json,css}": "vp check --fix",
  },
  plugins: [
    tailwindcss(),
    ...(isVitest ? [] : [tanstackStart(), nitro()]),
    // react's vite plugin must come after start's vite plugin
    react(),
    babel({ presets: [reactCompilerPreset()] }),
  ],
  resolve: {
    alias: {
      "~": srcPath,
    },
  },
  test: {
    // `happy-dom` rather than the `jsdom` named in .claude/rules/common/testing.md: it is
    // already a devDependency alongside @testing-library, serves the same purpose, and
    // adding jsdom would leave one of the two unused (a `vp run fallow` finding).
    environment: "happy-dom",
    include: ["src/**/*.test.ts", "src/**/*.test.tsx"],
    setupFiles: ["src/testing/setup.ts"],
  },
});
