import { fileURLToPath } from "node:url";

import babel from "@rolldown/plugin-babel";
import tailwindcss from "@tailwindcss/vite";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import react, { reactCompilerPreset } from "@vitejs/plugin-react";
import { nitro } from "nitro/vite";
import { RECOMMENDED_RULES, TANSTACK_START_RULES } from "oxlint-plugin-react-doctor";
import { defineConfig } from "vite-plus";

const reactDoctorRules = {
  ...RECOMMENDED_RULES,
  ...TANSTACK_START_RULES,
};

// `tanstackStart()` rewrites `createServerFn(...).handler(fn)` into a client RPC stub, which
// makes server-function handlers unimportable under Vitest, and its transform breaks plain
// unit tests. Nitro only matters for the deploy build. Drop both when Vitest is driving.
// See .claude/rules/common/testing.md.
const isVitest = process.env.VITEST === "true";

const srcPath = fileURLToPath(new URL("./src", import.meta.url));

export default defineConfig({
  fmt: {
    // `.agents/`, `.claude/`, `.cursor/` and `.serena/` are written by external tool
    // installers (skills-lock.json sync, Serena). Formatting them would be reverted on the
    // next sync and buries our own diffs under ~150 unrelated files. `src/data/cache/` is
    // generated by `vp run generate:passport` and must stay byte-identical to its output.
    ignorePatterns: [
      "**/routeTree.gen.ts",
      ".agents/**",
      ".claude/**",
      ".cursor/**",
      ".serena/**",
      "src/data/cache/**",
    ],
    sortImports: {
      partitionByComment: true,
    },
    sortPackageJson: {
      sortScripts: true,
    },
    sortTailwindcss: {
      functions: ["cn"],
    },
  },
  lint: {
    categories: {
      correctness: "error",
    },
    env: {
      browser: true,
      node: true,
    },
    // Same rationale as `fmt.ignorePatterns`: these are vendored by external tool installers.
    // `denyWarnings: true` means a warning in one of them would block every commit.
    ignorePatterns: ["**/routeTree.gen.ts", ".agents/**", ".claude/**", ".cursor/**", ".serena/**"],
    jsPlugins: [{ name: "react-doctor", specifier: "oxlint-plugin-react-doctor" }],
    options: {
      denyWarnings: true,
      typeAware: true,
      typeCheck: true,
    },
    overrides: [
      {
        files: ["src/router.tsx", "*.config.ts"],
        rules: {
          "no-default-export": "off",
        },
      },
      {
        files: ["src/routes/**"],
        rules: {
          "react-doctor/no-multi-comp": "off",
          "react-doctor/only-export-components": "off",
        },
      },
    ],
    plugins: ["react", "react-perf", "import", "jsx-a11y", "promise"],
    rules: {
      ...reactDoctorRules,
      "no-default-export": "error",
    },
  },
  staged: {
    "*.{js,jsx,ts,tsx,json,css}": "vp check --fix",
  },
  plugins: [
    tailwindcss(),
    ...(isVitest ? [] : [tanstackStart(), nitro()]),
    // react's vite plugin must come after start's vite plugin
    react(),
    babel({ presets: [reactCompilerPreset()] }),
  ],
  resolve: {
    alias: {
      "~": srcPath,
    },
  },
  test: {
    // `happy-dom` rather than the `jsdom` named in .claude/rules/common/testing.md: it is
    // already a devDependency alongside @testing-library, serves the same purpose, and
    // adding jsdom would leave one of the two unused (a `vp run fallow` finding).
    environment: "happy-dom",
    include: ["src/**/*.test.ts", "src/**/*.test.tsx"],
    setupFiles: ["src/testing/setup.ts"],
  },
});
