/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FreeRouteImport } from './routes/free'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PassportPersonaIdRouteImport } from './routes/passport.$personaId'

const FreeRoute = FreeRouteImport.update({
  id: '/free',
  path: '/free',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportPersonaIdRoute = PassportPersonaIdRouteImport.update({
  id: '/passport/$personaId',
  path: '/passport/$personaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/free': typeof FreeRoute
  '/passport/$personaId': typeof PassportPersonaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/free': typeof FreeRoute
  '/passport/$personaId': typeof PassportPersonaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/free': typeof FreeRoute
  '/passport/$personaId': typeof PassportPersonaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/free' | '/passport/$personaId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/free' | '/passport/$personaId'
  id: '__root__' | '/' | '/free' | '/passport/$personaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FreeRoute: typeof FreeRoute
  PassportPersonaIdRoute: typeof PassportPersonaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/free': {
      id: '/free'
      path: '/free'
      fullPath: '/free'
      preLoaderRoute: typeof FreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport/$personaId': {
      id: '/passport/$personaId'
      path: '/passport/$personaId'
      fullPath: '/passport/$personaId'
      preLoaderRoute: typeof PassportPersonaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FreeRoute: FreeRoute,
  PassportPersonaIdRoute: PassportPersonaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
