import { Schema } from "effect";

import satoRaw from "~/data/cache/sato-takumi.json";
import suzukiRaw from "~/data/cache/suzuki-haruka.json";
import takahashiRaw from "~/data/cache/takahashi-kenta.json";
import { PassportResult } from "~/data/schemas";

/**
 * The committed cache, statically imported so the bundler can see it — the demo must work with no
 * network and no API key. These files are generated by `vp run generate:passport`; never hand-edit
 * them. `src/data/cache-contract.test.ts` decodes all three against the current schemas, which is
 * the only thing that catches a schema change silently invalidating the cache.
 */
const CACHE_SOURCES = [
  { id: "sato-takumi", raw: satoRaw },
  { id: "suzuki-haruka", raw: suzukiRaw },
  { id: "takahashi-kenta", raw: takahashiRaw },
] as const;

export const CACHED_PERSONA_IDS = CACHE_SOURCES.map((source) => source.id);

/** Raw, undecoded sources — the contract test asserts the decode itself. */
export const RAW_CACHE_SOURCES = CACHE_SOURCES;

const decodeCache = Schema.decodeUnknownSync(PassportResult);

/**
 * Decoded eagerly at module load. A cache file that no longer matches the schema should fail loudly
 * at startup rather than halfway through a live demo.
 */
const CACHE = new Map<string, PassportResult>(
  CACHE_SOURCES.map(({ id, raw }) => [id, decodeCache(raw)]),
);

export function lookupCachedPassport(personaId: string): PassportResult | undefined {
  return CACHE.get(personaId);
}
