import { Schema } from "effect";
import type { ParseError } from "effect/ParseResult";

import satoRaw from "~/data/cache/sato-takumi.json";
import suzukiRaw from "~/data/cache/suzuki-haruka.json";
import takahashiRaw from "~/data/cache/takahashi-kenta.json";
import { ChefDataError } from "~/data/loaders";
import { PassportResult } from "~/data/schemas";

/**
 * The committed cache, statically imported so the bundler can see it — the demo must work with no
 * network and no API key. These files are generated by `vp run generate:passport`; never hand-edit
 * them. `src/data/cache-contract.test.ts` decodes all three against the current schemas, which is
 * the only thing that catches a schema change silently invalidating the cache.
 */
const CACHE_SOURCES = [
  { id: "sato-takumi", raw: satoRaw },
  { id: "suzuki-haruka", raw: suzukiRaw },
  { id: "takahashi-kenta", raw: takahashiRaw },
] as const;

export const CACHED_PERSONA_IDS = CACHE_SOURCES.map((source) => source.id);

/** Raw, undecoded sources — the contract test asserts the decode itself. */
export const RAW_CACHE_SOURCES = CACHE_SOURCES;

const decodeCache = Schema.decodeUnknownSync(PassportResult);

/**
 * Failing loudly at startup is right; failing with a raw `ParseError` is not. That value reaches
 * `__root.tsx`'s error boundary, which renders `error.message` — an English Effect parse dump on a
 * Japanese demo screen. `ChefDataError` names the file instead and keeps the parse detail in
 * `cause`, which is where the person who has to fix it will look.
 * See .claude/rules/typescript/effect-schema.md and audit #17 finding 16.
 */
export function decodeCacheSource(id: string, raw: unknown): PassportResult {
  try {
    return decodeCache(raw);
  } catch (cause) {
    throw new ChefDataError({
      cause: cause as ParseError,
      message: `事前生成キャッシュ cache/${id}.json がスキーマに一致しません。vp run generate:passport で再生成してください`,
      resource: `cache/${id}.json`,
    });
  }
}

/**
 * Decoded eagerly at module load. A cache file that no longer matches the schema should fail loudly
 * at startup rather than halfway through a live demo.
 */
const CACHE = new Map<string, PassportResult>(
  CACHE_SOURCES.map(({ id, raw }) => [id, decodeCacheSource(id, raw)]),
);

export function lookupCachedPassport(personaId: string): PassportResult | undefined {
  return CACHE.get(personaId);
}
